version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend_phase2/Dockerfile
    container_name: leadgen-api
    ports:
      - "5050:5050"
    env_file:
      - .env
    restart: always

  scraper:
    build: 
      context: ./phase_1
      dockerfile: Dockerfile
    container_name: scraper-api
    ports:
      - "5051:5050"
    env_file:
      - .env
    restart: always

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   container_name: leadgen-frontend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      # - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # ✅ mount certs into container
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always
