version: '3.8'

services:
  backend:
    build:
      context: ./backend_phase2
      dockerfile: Dockerfile
    container_name: leadgen-api
    ports:
      - "5050:5050"
    env_file:
      - .env
    restart: always

  scraper:
    build: 
      context: ./phase_1
      dockerfile: Dockerfile
    container_name: scraper-api
    ports:
      - "5050:5050"
    env_file:
      - .env
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always
